# Generated by Django 3.1.6 on 2021-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='foodname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
